language: node_js
notifications:
  email: false
script:
  - npm test
  - npm run build-docs
  # run sitemap tests after build to assert sitemap is correct
  - jest src/helpers/batfish/__tests__/sitemap.test.js
  - npm run lighthouse

# dependencies of lhci:
addons:
  chrome: stable
before_install:
  - npm install -g @lhci/cli@0.7.x
before_script:
  - git remote set-branches --add origin main
  - git fetch
