language: node_js
node_js:
  - '6'
sudo: false
notifications:
  email: false
cache:
  directories:
    - node_modules
git:
  depth: 3
before_install:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
