language: node_js
node_js:
  - '10'
sudo: false
notifications:
  email: false
cache:
  directories:
    - node_modules
git:
  depth: 3

script:
  - npm test
  - npm run build
  - cd demo
  - npm ci
  - npm run build
