language: node_js
sudo: false
notifications:
  email: false

scripts:
  - npm test
  - npm run build-docs
  # run sitemap tests after build to assert sitemap is correct
  - jest src/helpers/batfish/__tests__/sitemap.test.js

before_install:
  - npm install -g npm@7
