# based on https://github.com/mapbox/mapbox-gl-directions/blob/master/.circleci/config.yml
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.4
  browser-tools: circleci/browser-tools@1.4.0

workflows:
  default:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/node:14.20.0
    environment:
      MBX_CI_DOMAIN: o619qyc20d.execute-api.us-east-1.amazonaws.com
    steps:
      - checkout
      - run: curl -Ls https://mapbox-release-engineering.s3.amazonaws.com/mbx-ci/latest/mbx-ci-linux-amd64 > mbx-ci && chmod 755 ./mbx-ci
      - run: ./mbx-ci npm token --write-file
      - run:
          name: Install Dependencies
          command: |
            npm ci
