/* eslint-disable */
'use strict';
// DO NOT MODIFY DIRECTLY
// This file is generated by a script in bin.

function getTestCases(m) {
  if (m.testCases) {
    return m.testCases;
  }
  if (m.default && m.default.testCases) {
    return m.default.testCases;
  }
  throw new Error('Every test case module needs a testCases export.');
}

module.exports = [
  { title: 'BackToTopButton', cases: getTestCases(require('./../components/back-to-top-button/__tests__/back-to-top-button-test-cases.js')) },
  { title: 'OverviewHeader', cases: getTestCases(require('./../components/overview-header/__tests__/overview-header-test-cases.js')) },
  { title: 'TutorialCard', cases: getTestCases(require('./../components/tutorial-card/__tests__/tutorial-card-test-cases.js')) }
];
