const prepareSitemap = require('../sitemap');
const { pages } = require('./fixtures/data.json');

const siteBasePath = '/dr-ui';

describe('prepareSitemap', () => {
  it('works', () => {
    const ignoreFile = prepareSitemap({ pages, siteBasePath }).map((f) =>
      f.replace(process.cwd(), '')
    );
    expect(ignoreFile).toEqual(['/_site/index.html']);
  });

  it('advanced, exclude demos generated by webpack loader', () => {
    const ignoreFile = [
      ...prepareSitemap({ pages, siteBasePath }),
      `${process.cwd()}/_site/assets/`
    ].map((f) => f.replace(process.cwd(), ''));
    expect(ignoreFile).toEqual(['/_site/index.html', '/_site/assets/']);
  });

  it('with docsPath', () => {
    const ignoreFile = prepareSitemap({
      pages,
      siteBasePath,
      docsPath: 'docs'
    }).map((f) => f.replace(process.cwd(), ''));
    expect(ignoreFile).toEqual(['/docs/_site/index.html']);
  });

  it('with outputDirectory', () => {
    const ignoreFile = prepareSitemap({
      pages,
      siteBasePath,
      outputDirectory: '_batfish_site'
    }).map((f) => f.replace(process.cwd(), ''));
    expect(ignoreFile).toEqual(['/_batfish_site/index.html']);
  });
});
