import { Helmet } from 'react-helmet-async';
import React from 'react';

function PageHelmet() {
  return (
    <Helmet>
      <meta charSet="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      {/* Favicon */}
      <link
        rel="apple-touch-icon"
        sizes="180x180"
        href="https://static-assets.mapbox.com/branding/favicon/v2/apple-touch-icon.png?v=gAd4JjrGWl"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="32x32"
        href="https://static-assets.mapbox.com/branding/favicon/v2/favicon-32x32.png?v=gAd4JjrGWl"
      />
      <link
        rel="icon"
        type="image/png"
        sizes="16x16"
        href="https://static-assets.mapbox.com/branding/favicon/v2/favicon-16x16.png?v=gAd4JjrGWl"
      />
      <link
        rel="manifest"
        href="https://static-assets.mapbox.com/branding/favicon/v2/site.webmanifest?v=gAd4JjrGWl"
      />
      <link
        rel="mask-icon"
        href="https://static-assets.mapbox.com/branding/favicon/v2/safari-pinned-tab.svg?v=gAd4JjrGWl"
        color="#4264fb"
      />
      <link
        rel="shortcut icon"
        href="https://static-assets.mapbox.com/branding/favicon/v2/favicon.ico?v=gAd4JjrGWl"
      />
      <meta name="msapplication-TileColor" content="#ffffff" />
      <meta
        name="msapplication-config"
        content="https://static-assets.mapbox.com/branding/favicon/v2/browserconfig.xml?v=gAd4JjrGWl"
      />
      <meta name="theme-color" content="#ffffff" />
      {/* Pinterest domain verification */}
      <meta name="p:domain_verify" content="57838af58c8045c2c024bc2f9d1577f9" />
      {/* Google domain verification */}
      <meta
        name="google-site-verification"
        content="umPiCFUc_EX8CJ7xWQDPgQwApDxNi59w6riFZPNZj4w"
      />
      {/* Twitter */}
      <meta name="twitter:site" content="@Mapbox" />
      <meta property="og:site_name" content="Mapbox" />
      <script
        src="https://widget.kapa.ai/kapa-widget.bundle.js"
        data-website-id="b96d25fb-28f1-4bea-a2d6-70a31920b822"
        data-project-name="Mapbox"
        data-project-color="#000000"
        data-project-logo="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiIgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiBmaWxsPSIjRkZGIj48cGF0aCBkPSJNMTYgMEM3LjE2MyAwIDAgNy4xNjMgMCAxNnM3LjE2MyAxNiAxNiAxNiAxNi03LjE2MyAxNi0xNlMyNC44MzcgMCAxNiAwem03LjU5NSAxOS45MjRDMTguMTI0IDI1LjM5NSA4LjM1IDIzLjY1IDguMzUgMjMuNjVzLTEuNzY0LTkuNzU1IDMuNzI2LTE1LjI0NGMzLjA0Mi0zLjA0MiA4LjA4LTIuOTE2IDExLjI2Ny4yNTJzMy4yOTQgOC4yMjUuMjUyIDExLjI2N3ptLTUuNzYtLjk3MmwxLjU2Ni0zLjIyMiAzLjIyMi0xLjU2Ni0zLjIyMi0xLjU2Ni0xLjU2Ni0zLjIyMi0xLjU2NiAzLjIyMi0zLjIyMiAxLjU2NiAzLjIyMiAxLjU2NnoiLz48L3N2Zz4="
        data-modal-override-open-class="chakra-input"
        data-search-mode-enabled="false"
        data-modal-disclaimer="This is a custom LLM for Mapbox with access to all developer docs (docs.mapbox.com) and all Stackoverflow questions (stackoverflow.com/questions/tagged/mapbox). Please note that answers are generated by AI and may not be fully accurate, so please use your best judgement."
      ></script>
    </Helmet>
  );
}

export { PageHelmet };
